BaseUrl= "https://aphorya.github.io/"
LanguageCode= "fr-FR"
Title= "Aphorya"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2022"
canonifyurls = true

[author]
  name = "RaKk0o"

[permalinks]
    post = "/post/:year/:month/:day/:slug"

[params]
  description = "Rejoignez-nous !"
  cover = "images/bannière.png"
  author = "RaKk0o"
  authorlocation = ""
  authorwebsite = "https://rakk0o.aphorya.fr/"
  bio= "my bio"
  logo = "images/Logo.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "RaKk0o"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  mainSections = ["post"]
