baseURL: "https://aphorya.github.io"
languageCode: "fr-fr"
title: "APHORYA"
theme: hugo-profile

Paginate: 3

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1


params:
  socialShare: false

  title: "Aphorya"
  description: This blog gathers the different projects I realized during my schooling but also as personnal projetcs.
  # staticPath: ""  # The path to serve the static files from
  favicon: "/img/logo_e.png"

  theme:
    disableThemeToggle: false
    defaultTheme: "dark" # light

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Bonjour, bienvenue sur"
    title: "Aphorya !"
    subtitle: "Aphorya est une communauté discord de joueurs Français."
    content: "Nous nous concentrons souvent sur Valorant, Fortnite, Among Us, Grand Theft Auto V, Minecraft, Overwatch 2, Sea of Thieves, League of Legends. Mais nous aimons varier régulièrement."
    image: "/img/logo_e.png"
    button:
      enable: true
      name: "Nous rejoindre"
      url: "https://discord.gg/EGZM6fE"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Aphorya

  # About
  about:
    enable: true
    title: "A propos"
    image: "/img/logo_e.png"
    content: |-
      Nous sommes une petite équipe composée de tous niveaux. Nous faisons des sessions de jeux assez régulièrement en essayant toujours de garder une bonne ambiance chill.
    skills:
      enable: true
      title: "Quelques jeux auxquels nous avons joué récemment :"
      items:
        - "Valorant"
        - "Fortnite"
        - "Among Us"
        - "Grand Theft Auto V"
        - "Minecraft"
        - "Overwatch 2"
        - "Sea of Thieves" 
        - "League of Legends"
        - "Golf Gang"
        - "Krunker"
        - "Gartic Phone"
        - "Tom Clancy's Rainbow Six: Siege"
  
  # Education
  education:
    enable: true
    title: "Projets"
    # index: true
    items:
      - title: "Réseau social"
        school:
          name: "APHORYA"
          url: ""
        date: "En cours"
        content: |-
          Le but premeir de ce projet est de rassembler les joueurs. 
          Cela permettrai de rencontrer des gens, mais également de trouver des partenaires et d'éviter le matchmaking toxic de certains jeux.
      - title: "Serveur Minecraft"
        school:
          name: "APHOCRAFT"
          url: ""
        date: "En cours"
        content: |-
          Ce serveur minecraft serait exclusivement disponible pour les joueurs présents sur le serveur Aphorya dans un premier temps, avant d'être ouvert à tous le monde. Au programme : Survie, Donjons, Mini-jeux, et bien d'autres choses.

    
  #Contact
  contact:
    enable: true
    title: "Contact"
    content: Si vous souhaitez me contacter pour avoir plus d'informations à propos du projet, n'hésitez pas.
    email: contact@aphorya.fr
    btnName: Mail

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/Aphorya
      discord: https://discord.gg/EGZM6fE