baseURL: "https://aphorya.github.io"
languageCode: "fr-fr"
title: "APHORYA"
theme: hugo-profile

Paginate: 3

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1


params:
  socialShare: false

  title: "Aphorya"
  description: This blog gathers the different projects I realized during my schooling but also as personnal projetcs.
  # staticPath: ""  # The path to serve the static files from
  favicon: "/img/logo_e.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Bonjour, bienvenue sur"
    title: "Aphorya !"
    subtitle: "Aphorya est une communauté discord de joueurs Français."
    content: "Nous nous concentrons souvent sur Valorant, Fortnite, Among Us, Grand Theft Auto V, Minecraft, Overwatch 2, Sea of Thieves, League of Legends. Mais nous aimons varier régulièrement."
    image: "/img/logo_e.png"
    button:
      enable: true
      name: "Nous rejoindre"
      url: "https://discord.gg/EGZM6fE"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Aphorya

  # About
  about:
    enable: true
    title: "A propos"
    image: "/img/logo_e.png"
    content: |-
      Nous sommes une petite équipe composée de tous niveaux. Nous faisons des sessions de jeux assez régulièrement en essayant toujours de garder une bonne ambiance chill.
    skills:
      enable: true
      title: "Quelques jeux auxquels nous avons joué récemment :"
      items:
        - "Valorant"
        - "Fortnite"
        - "Among Us"
        - "Grand Theft Auto V"
        - "Minecraft"
        - "Overwatch 2"
        - "Sea of Thieves" 
        - "League of Legends"
        - "Golf Gang"
        - "Krunker"
        - "Gartic Phone"
        - "Tom Clancy's Rainbow Six: Siege"

  # Experience
  experience:
    enable: false
    title: "experience"
    items:
      - job: "Networks and Infrastructure (Internship)"
        company: "Linguanomics RD"
        companyUrl: "https://www.linguanomics.com/"
        date: "Jan 2022 - Apr 2022"
        content: |
          Setting up a VPN, using Docker. Automating installations via Ansible and Kubernetes. Virtualization.
        featuredLink:
          enable: true
          name: "Letter of appreciation (fr)"
          url: "https://drive.google.com/file/d/1of4V3SsI3ZlIMb_W6Yv9B1Wo5f7FJGfj/view?usp=sharing"

      - job: "User support (Internship)"
        company: "Faurecia"
        companyUrl: "http://faurecia.com/"
        date: "Apr 2021 - Jul 2021"
        content: |
          Worked in an IT team as user support, took part in internal migrations, routines, ITOPE audit preparation, Raspberry Pi configuration.
      
      - job: "Summer auxiliary"
        company: "Société générale"
        companyUrl: "https://particuliers.societegenerale.fr/"
        date: "July 2021"
        content: |
          Greeted and gave physical and telephone orientation to customers. Performed routine operations at the counter according to safety rules and instructions.

      - job: "Order picker"
        company: "Vynex"
        companyUrl: "https://www.rocket.eu/"
        date: "Sep 2020 - Dec 2021"
        content: |
          Picking and gathering of furniture hardware items in the quantity specified by the order prior to order shipment.
  # Education
  education:
    enable: true
    title: "Projets"
    # index: true
    items:
      - title: "Réseau social"
        school:
          name: "APHORYA"
          url: ""
        date: "In progress"
        content: |-
          Le but premeir de ce projet est de rassembler les joueurs. 
          Cela permettrai de rencontrer des gens, mais également de trouver des partenaires et d'éviter le matchmaking toxic de certains jeux.
      - title: "Serveur Minecraft"
        school:
          name: "APHOCRAFT"
          url: ""
        date: "In progress"
        content: |-
          Ce serveur minecraft serait exclusivement disponible pour les joueurs présents sur le serveur Aphorya dans un premier temps, avant d'être ouvert à tous le monde. Au programme : Survie, Donjons, Mini-jeux, et bien d'autres choses.

  # Achievements
  achievements:
    enable: false
    items:
      - title: CSS
        content: HackerRank certificate, obtained on 10/04/2022.
        url: https://www.hackerrank.com/certificates/e87996b8aa23

      - title: Python (Basic)
        content: HackerRank certificate, otained on 10/03/2022.
        url: https://www.hackerrank.com/certificates/3e96baaef945

      - title: SQL (Basic)
        content: HackerRank certificate, otained on 10/03/2022.
        url: https://www.hackerrank.com/certificates/ffe369a0bb6e

      - title: Cisco CCNA1
        content: Obtained on 05/02/2021.
        url: https://drive.google.com/file/d/1vcvTn1GfK8FJ6660m45GcfArKIjkxuOn/view?usp=sharing

      - title: Driving licence
        # content: 
        # url: 
      
      - title: BIA
        content: Aeronautical initiation certificate.
        # url: 

  # projects
  projects:
    enable: false

# personnal project
    items:
      - title: Aphorya (personnal)
        content: Social network oriented towards the gaming community.
        image: /img/projects/aphorya.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/aphorya/

      - title: Filebackup (personnal)
        content: File storage web application.
        image: /img/projects/fbackup.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/filebackup/

# school projects    
      - title: Storage and Big Data (school)
        content: Connection to different databases using Talend, data modeling with Power Bi.
        image: /img/projects/bigdata.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/bigdata/

      - title: System programming (school)
        content: Realization of 3 versions of a backup software using C#.
        image: /img/projects/sysprog.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/sysprog/
      
      - title: Information system (school)
        content: Administration of an I.S. using PowerShell, Firewall, VPN,...
        image: /img/projects/isystem.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/isystem/
                
      - title: Web development (school)
        content: Creation of LinkedIn type website using HTML, CSS, PHP, JS.
        image: /img/projects/webdev.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/webdev/
                
      - title: Network (school)
        content: Configuration of networks via Packet Tracer using CISCO.
        image: /img/projects/network.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/network/
                
      - title: Object-oriented programming (school)
        content: Realization of a management application using C++.
        image: /img/projects/oop.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/oop/
                
      - title: Embedded system (school)
        content: Realization of a weather station using Arduino.
        image: /img/projects/embeddedsystem.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/embeddedsystem/
                          
      - title: Industry (school)
        content: Study of the conception to the production of a product.
        image: /img/projects/industry.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/industry/
                          
      - title: Data Base (school)
        content: Creation, management, and queries in the database using MySQL.
        image: /img/projects/database.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/database/
                          
      - title: Signal (school)
        content: Realization of communication programs using Python.
        image: /img/projects/signal.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/signal/
                          
      - title: Electronics (school)
        content: Realization of a security system using Arduino.
        image: /img/projects/electronics.png
        featured:
          name: Read more
          link: https://rakk0o.aphorya.fr/blogs/electronics/

  #Contact
  contact:
    enable: true
    content: Si vous souhaitez me contacter pour avoir plus d'informations à propos du projet, n'hésitez pas.
    email: contact@aphorya.fr
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/Aphorya
      discord: https://discord.gg/EGZM6fE